
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/codespace/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-1041-azure - x86_64
...
